import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const code=readFileSync(new URL('../public/tv.js',import.meta.url),'utf8');
class Element{constructor(){this.textContent='';this._html='';this.style={setProperty:(k,v)=>{this.style[k]=v}};this.classes=new Set();this.classList={add:c=>this.classes.add(c),remove:c=>this.classes.delete(c)};this.children=[];this.offsetWidth=1682;this.imgs=[{},{}];}set innerHTML(s){this._html=s;this.children=[new Element(),new Element()];}get innerHTML(){return this._html;}querySelectorAll(){return this.imgs;}addEventListener(){}}
function setup(ads=['/ads/pub1.png','/ads/pub2.png','/ads/pub10.png'],broken=false){const elements=new Map();const get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id)};get('league-dots').children=Array.from({length:5},()=>new Element());const intervals=[];const timeouts=new Map();let timeoutId=0,fetchCount=0;const data={version:1,leagues:['PT','UK','ES','IT','DE'].map((country,i)=>({country,name:'LEAGUE '+i,rows:Array.from({length:18},(_,j)=>({position:j+1,name:'Team '+j,played:5,points:j})),updatedAt:new Date().toISOString()})),fixtures:{data:Array.from({length:9},(_,j)=>({home:'Home',away:'Away',matchday:9,utcDate:'2099-10-'+String(10+j).padStart(2,'0')+'T20:15:00Z',timeConfirmed:true})),updatedAt:new Date().toISOString()},results:{data:[{home:'Home',away:'Away',matchday:8,homeScore:1,awayScore:0}],updatedAt:new Date().toISOString()},markets:[],pending:{crypto:true,equities:true}};const storage=new Map();const context={document:{getElementById:get,addEventListener(){},documentElement:{},hidden:false},window:{innerWidth:1920,innerHeight:1080,addEventListener(){}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setInterval:(fn,ms)=>{intervals.push({fn,ms});return intervals.length;},setTimeout:(fn,ms)=>{timeouts.set(++timeoutId,{fn,ms});return timeoutId;},clearTimeout:id=>timeouts.delete(id),requestAnimationFrame:fn=>fn(),Image:class{set src(v){queueMicrotask(()=>{if(broken)this.onerror();else this.onload();})}},fetch:async url=>{fetchCount++;return {ok:true,json:async()=>url==='/api/broadcast'?data:{ads,version:1}}},AbortController,Promise,Date,JSON,Number,String,Math,Error};vm.runInNewContext(code,context);return {elements,get,intervals,timeouts,context,data,get fetchCount(){return fetchCount}};}
async function flush(){for(let i=0;i<12;i++)await Promise.resolve();}
test('1920x1080 and 1366x768 scale fit; table/fixtures paginate; ticker duplicates match',async()=>{const s=setup();await flush();assert.equal(s.get('broadcast').style['--tv-scale'],'1');assert.match(s.get('table').innerHTML,/Team 9/);assert.doesNotMatch(s.get('table').innerHTML,/Team 10/);assert.equal((s.get('fixtures').innerHTML.match(/class="match"/g)||[]).length,5);s.intervals.find(i=>i.ms===18000).fn();assert.match(s.get('table').innerHTML,/Team 17/);s.intervals.find(i=>i.ms===18000).fn();assert.equal(s.get('league-country').textContent,'UK');s.context.window.innerWidth=1366;s.context.window.innerHeight=768;const scale=Math.min(1366/1920,768/1080);assert.ok(1920*scale<=1366&&1080*scale<=768);assert.equal(108+797+28+65+82,1080);const html=s.get('results-track').innerHTML;assert.equal((html.match(/Home/g)||[]).length,2);});
test('8 simulated hours preserve slideshow loop and bounded timers',async()=>{const s=setup();await flush();assert.equal(s.get('ad-count').textContent,'01 / 03');const ad=s.intervals.find(i=>i.ms===10000);for(let ms=1000;ms<=28800000;ms+=1000){for(const interval of s.intervals)if(ms%interval.ms===0)interval.fn();await flush();}assert.equal(s.get('ad-count').textContent,'01 / 03');assert.ok(s.timeouts.size<=1);assert.equal(s.intervals.length,6);assert.ok(s.fetchCount<660);});
test('single advertisement remains visible without repeated image swaps',async()=>{const s=setup(['/ads/pub1.png']);await flush();const ad=s.intervals.find(i=>i.ms===10000);for(let i=0;i<12;i++){ad.fn();await flush();}assert.equal(s.get('ad-count').textContent,'01 / 01');assert.equal(s.get('ad-b').imgs[1].src,'/ads/pub1.png');});
test('failed images keep welcome/current content and timers recover',async()=>{const s=setup(['/ads/missing.png'],true);await flush();s.intervals.find(i=>i.ms===10000).fn();await flush();assert.equal(s.get('ad-count').textContent,'');assert.equal(s.get('ad-b').classes.has('active'),false);assert.ok(s.timeouts.size<=1);});
