export const leagues=[{code:'PPL',name:'PRIMEIRA LIGA',country:'PT',file:'pt.1'},{code:'PL',name:'PREMIER LEAGUE',country:'UK',file:'en.1'},{code:'PD',name:'LA LIGA',country:'ES',file:'es.1'},{code:'SA',name:'SERIE A',country:'IT',file:'it.1'},{code:'BL1',name:'BUNDESLIGA',country:'DE',file:'de.1'}];
const aliases={'Sport Lisboa e Benfica':'Benfica','SL Benfica':'Benfica','Sporting Clube de Portugal':'Sporting CP','Sporting CP':'Sporting CP','Sporting Clube de Braga':'SC Braga','Sporting Braga':'SC Braga','Vitória Guimarães':'Vitória SC','Vitória SC':'Vitória SC','CF Estrela da Amadora':'Estrela Amadora','Académico de Viseu FC':'Académico Viseu','GD Estoril Praia':'Estoril Praia','FC Bayern München':'Bayern München','Borussia Mönchengladbach':'Mönchengladbach','Manchester United FC':'Man. United','Manchester City FC':'Man. City','Nottingham Forest FC':'Nott. Forest','Brighton & Hove Albion FC':'Brighton','Wolverhampton Wanderers FC':'Wolves','Club Atlético de Madrid':'Atlético Madrid','Athletic Club':'Athletic Bilbao'};
export function shortName(name){return aliases[name]||String(name||'').replace(/ FC$/,'').replace(/^FC /,'').replace(/Football Club/g,'').trim();}
export function officialTable(data,league){const total=data.standings?.find(s=>s.type==='TOTAL');if(!total?.table?.length)throw new Error('No standings');return {...league,official:true,season:data.season?.startDate?.slice(0,4),rows:total.table.map(t=>({position:t.position,name:shortName(t.team.shortName||t.team.name),points:t.points,played:t.playedGames,gd:t.goalDifference}))};}
export function officialMatches(data){if(!Array.isArray(data.matches))throw new Error('Invalid matches');return data.matches.map(m=>({id:m.id,home:shortName(m.homeTeam.shortName||m.homeTeam.name),away:shortName(m.awayTeam.shortName||m.awayTeam.name),utcDate:m.utcDate,status:m.status,matchday:m.matchday,homeScore:m.score?.fullTime?.home,awayScore:m.score?.fullTime?.away,timeConfirmed:m.status==='TIMED'||m.status==='FINISHED'}));}
export function selectFixtures(matches,now=Date.now()){const future=matches.filter(m=>['SCHEDULED','TIMED'].includes(m.status)&&Date.parse(m.utcDate)>now).sort((a,b)=>Date.parse(a.utcDate)-Date.parse(b.utcDate));if(!future.length)return [];const matchday=future[0].matchday;return future.filter(m=>m.matchday===matchday).slice(0,12);}
export function selectResults(matches){const finished=matches.filter(m=>m.status==='FINISHED'&&Number.isInteger(m.homeScore)&&Number.isInteger(m.awayScore)).sort((a,b)=>Date.parse(b.utcDate)-Date.parse(a.utcDate));if(!finished.length)return [];const round=Math.max(...finished.map(m=>Number(m.matchday)||0));return finished.filter(m=>Number(m.matchday)===round).sort((a,b)=>Date.parse(a.utcDate)-Date.parse(b.utcDate));}
export function coinloreQuotes(data,now=new Date().toISOString()){if(!Array.isArray(data))throw new Error('Invalid crypto');const quotes=['BTC','ETH','SOL'].map(symbol=>{const c=data.find(t=>t.symbol===symbol);const price=Number(c?.price_usd),change=Number(c?.percent_change_24h);if(!c||!Number.isFinite(price)||price<=0||!Number.isFinite(change))throw new Error('Incomplete crypto');return {symbol,name:c.name,price,change,basis:'24H',asOf:now,source:'CoinLore'};});return quotes;}
export function oilQuote(data){const values=data.response?.data?.filter(d=>d.series==='RWTC'&&d.value!==null&&Number.isFinite(Number(d.value))).sort((a,b)=>b.period.localeCompare(a.period));if(values?.length<2)throw new Error('Incomplete oil');const price=Number(values[0].value),prev=Number(values[1].value);if(price<=0||prev<=0)throw new Error('Invalid oil');return [{symbol:'WTI',name:'Petróleo',price,change:(price/prev-1)*100,basis:'DIÁRIO · '+values[0].period,asOf:values[0].period,source:'EIA'}];}
export function equityQuotes(data){const symbols=['AAPL','MSFT','NVDA','AMZN','GOOGL'];return symbols.map(symbol=>{const q=data[symbol];const price=Number(q?.close),change=Number(q?.percent_change);if(!q||q.status==='error'||!Number.isFinite(price)||price<=0||!Number.isFinite(change))throw new Error('Invalid stock quote');return {symbol,name:q.name,price,change,basis:'SESSÃO · '+String(q.datetime||''),asOf:q.datetime,source:'Twelve Data'};});}
export function cmcQuotes(response){if(Number(response.status?.error_code||0)!==0)throw new Error('Crypto unavailable');return ['1','1027','5426'].map(id=>{const item=Array.isArray(response.data)?response.data.find(x=>String(x.id)===id):response.data?.[id];const q=Array.isArray(item?.quote)?item.quote.find(x=>x.symbol==='USD'):item?.quote?.USD;const price=Number(q?.price),change=Number(q?.percent_change_24h);if(!q||!Number.isFinite(price)||price<=0||!Number.isFinite(change))throw new Error('Incomplete crypto');return {symbol:item.symbol,name:item.name,price,change,basis:'24H',asOf:q.last_updated,source:'CoinMarketCap'};});}
