import { env } from 'cloudflare:workers';
import { cached } from '../../../lib/cache.mjs';
import { leagues, officialTable, officialMatches, selectFixtures, selectResults, cmcQuotes, oilQuote, equityQuotes } from '../../../lib/providers.mjs';
type Entry={payload:any;updatedAt:number;nextAttempt:number};
const memory=new Map<string,Entry>();
const inFlight=new Map<string,Promise<any>>();
let footballBlockedUntil=0;
const runtime=env as unknown as {BUCKET?:R2Bucket;FOOTBALL_DATA_TOKEN?:string;EIA_API_KEY?:string;CMC_API_KEY?:string;TWELVE_DATA_KEY?:string;EQUITIES_DISPLAY_LICENSED?:string};
const store={async get(key:string){try{if(runtime.BUCKET){const object=await runtime.BUCKET.get('cache-v1/'+key+'.json');if(object)return await object.json<Entry>();}}catch{}return memory.get(key);},async put(key:string,value:Entry){memory.set(key,value);if(runtime.BUCKET)try{await runtime.BUCKET.put('cache-v1/'+key+'.json',JSON.stringify(value));}catch{}}};
function shared(key:string,ttl:number,loader:()=>Promise<any>){const existing=inFlight.get(key);if(existing)return existing;const p=cached(store,key,ttl,loader).finally(()=>inFlight.delete(key));inFlight.set(key,p);return p;}
async function request(url:string,headers:Record<string,string>={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{headers,signal:controller.signal});if(!r.ok){const e=new Error('Provider unavailable') as Error&{retryAfter:number};e.retryAfter=Number(r.headers.get('Retry-After')||120)*1000;throw e;}return await r.json();}finally{clearTimeout(timer);}}
async function football(path:string){const now=Date.now();if(!runtime.FOOTBALL_DATA_TOKEN||now<footballBlockedUntil){const e=new Error('Football pending') as Error&{retryAfter:number};e.retryAfter=Math.max(120000,footballBlockedUntil-now);throw e;}const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch('https://api.football-data.org/v4/'+path,{headers:{'X-Auth-Token':runtime.FOOTBALL_DATA_TOKEN.trim()},signal:controller.signal});const available=r.headers.get('X-RequestsAvailable');const reset=Math.max(1,Number(r.headers.get('X-RequestCounter-Reset')||60));if(r.status===429||(available!==null&&Number(available)<=0))footballBlockedUntil=Date.now()+reset*1000;if(!r.ok){const e=new Error('Football unavailable') as Error&{retryAfter:number};e.retryAfter=Math.max(Number(r.headers.get('Retry-After')||reset)*1000,120000);throw e;}return await r.json();}finally{clearTimeout(timer);}}
export async function GET(){try{
 const tables=[];
 // Sequential calls stay below free-tier bursts; subsequent TV polls hit R2.
 for(const league of leagues){const result=await shared('standings-'+league.code,30*60000,async()=>officialTable(await football('competitions/'+league.code+'/standings'),league));tables.push({...league,...result.data,updatedAt:result.updatedAt,stale:result.stale,rows:result.data?.rows||[]});}
 const results=await shared('results-PPL',15*60000,async()=>selectResults(officialMatches(await football('competitions/PPL/matches?status=FINISHED'))));
 const fixtures=await shared('fixtures-PPL',60*60000,async()=>officialMatches(await football('competitions/PPL/matches?status=SCHEDULED,TIMED')));
 const oil=await shared('oil-WTI',24*60*60000,async()=>{const q=new URLSearchParams({'api_key':runtime.EIA_API_KEY||'DEMO_KEY','frequency':'daily','data[0]':'value','facets[series][]':'RWTC','sort[0][column]':'period','sort[0][direction]':'desc','length':'5'});return oilQuote(await request('https://api.eia.gov/v2/petroleum/pri/spt/data/?'+q));});
 const crypto=await shared('crypto-CMC',5*60000,async()=>cmcQuotes(await request('https://pro-api.coinmarketcap.com/'+(runtime.CMC_API_KEY?'':'public-api/')+'v3/cryptocurrency/quotes/latest?id=1,1027,5426&convert=USD',runtime.CMC_API_KEY?{'X-CMC_PRO_API_KEY':runtime.CMC_API_KEY}:{})));

 const equities=runtime.EQUITIES_DISPLAY_LICENSED==='true'&&runtime.TWELVE_DATA_KEY?await shared('equities',15*60000,async()=>equityQuotes(await request('https://api.twelvedata.com/quote?symbol=AAPL,MSFT,NVDA,AMZN,GOOGL&apikey='+encodeURIComponent(runtime.TWELVE_DATA_KEY!)))):{data:[],updatedAt:null,stale:false};
 return Response.json({version:1,generatedAt:new Date().toISOString(),leagues:tables,results:{...results,data:results.data||[]},fixtures:{...fixtures,data:selectFixtures(fixtures.data||[])},markets:[{kind:'crypto',...crypto},{kind:'equities',...equities},{kind:'oil',...oil}],attribution:['Football data provided by the Football-Data.org API','WTI: U.S. EIA'],pending:{crypto:false,equities:runtime.EQUITIES_DISPLAY_LICENSED!=='true'}},{headers:{'Cache-Control':'no-store'}});
 }catch{return Response.json({version:1,unavailable:true},{headers:{'Cache-Control':'no-store'}});}}
